### ISSUE TITLE
Lottie Plugin shows on elementor, but does not work

### ISSUE THREAD

**Issue by stevensriwi1** [over-engineer/lottie-for-elementor#18]
Hi there,

My Lottie plugin shows on elementor. But when I uploaded the json file installed from " https://lottiefiles.com/24313-business-man-beatriz " it does not show the svg on the screen.

![image](https://user-images.githubusercontent.com/54009817/84611897-6525e880-af02-11ea-8af4-54349902bfc3.png)

Hope to hear from you soon.

Thank you,
Steven

**Comment by over-engineer** [comment]
Hey @stevensriwi1,

I’m sorry for my late reply.

Would you mind answering the following?

1. Are there any errors on the console? (on Google Chrome, <kbd>CTRL</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd> on Windows, or <kbd>CMD</kbd> + <kbd>Option</kbd> + <kbd>J</kbd> on macOS)
2. Does it show up on the frontend? (the “Preview” option of Elementor)
3. If possible, could you please share a link to your website so I can investigate it in more depth? If you don’t want to post it publicly here, feel free to email me at dev@over-engineer.com

**Comment by over-engineer** [comment]
Hello again!

~It’s been a while since the last comment on this, so I’ll assume your questions have been answered.~

~I’m going to close this, but please don’t hesitate to reach out if you have any more questions 😄~

**Edit:** This was resolved over email (turned out to be a “Mixed Content” issue, similar to #12)
